mysite/myapp/urls.py
from django.urls import path
from .views import index, indexItem

app_name = "myapp"

urlpatterns = [
    path('', index, name='index'),
    path('<int:my_id>/', indexItem, name='detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("myapp/", include('myapp.urls', namespace="myapp"))
]

mysite/myapp/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

mysite/myapp/views.py
from django.shortcuts import render
from .models import Product
from django.http import HttpResponse

def index(request):
    items = Product.objects.all()
    context = {'items': items}
    return render(request, 'myapp/home.html', context=context)

def indexItem(request, my_id):
    item = Product.objects.get(id = my_id)
    context = {'item': item}
    return render(request, 'myapp/detail.html', context=context)

mysite/myapp/templates/myapp/detail.html
{% extends 'main.html' %}

{% block title %} detail {% endblock %}

{% block content %}
<h1>
 This is the detail page
</h1>
<h2>
 {{ item.name }} / {{ item.description }} / {{ item.price }}
</h2>
{% endblock %}

mysite/myapp/templates/myapp/home.html
{% extends 'main.html' %}
{% block title %} home {% endblock %}

{% block content %}
<h1>
 This is the items that will be added
</h1>
<h2>
 {% for item in items %}
    <a href = "{% url 'myapp:detail' item.id %} ">
     {{ item.id }}.{{ item.name }} / {{ item.description }} / {{ item.price }} <br>
    </a>
 {% endfor %}
</h2>
{% endblock %}

mysite/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> my site - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>